Adding AlmaLinux
Punderthings/fossfoundation pull request #20
Opened 2024-02-19 21:43 UTC by bennyvasquez

I'm hoping I did things right here! Happy to take feedback if I need to adjust anything.

2024-02-20 00:04 UTC, ShaneCurcuru requested changes
Thanks - a couple of errors to fix first.  Also, do you want to add links to your brandPolicy, and any code of conduct you have?

2024-02-20 00:04 UTC, ShaneCurcuru commented on _foundations/almalinux.md
> +licenses: https://www.osgeo.org/about/licenses/
Is this really the correct license link? 😸

2024-02-20 00:04 UTC, ShaneCurcuru commented on _foundations/almalinux.md
> +ethicsPolicy:https://almalinux.org/p/foundation-board-operations-and-ethics/
Typo, needs a space after the first colon (we still need to add linting to commit checks)

2024-02-21 14:42 UTC, bennyvasquez commented
@ShaneCurcuru Good catch on both of those! Can you tell I was finding examples in other listings to help? :D This push should fix them both, I think.

2024-02-22 20:35 UTC, merged